#ifndef CERT_H

#define CERT_H

//DigiCert root certificate has expiry date of 10 Nov 2031
const char * rootCACertificate = \
"-----BEGIN CERTIFICATE-----\n" \
"MIIFGDCCBACgAwIBAgISBKCoBlNhIdbw+Sfn0ATx3iitMA0GCSqGSIb3DQEBCwUA\n"
"MDMxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MQwwCgYDVQQD\n"
"EwNSMTAwHhcNMjQxMTE1MDkyMjE2WhcNMjUwMjEzMDkyMjE1WjAiMSAwHgYDVQQD\n"
"Exdzb25nYXRlY2hub2xvZ2llcy5jby5rZTCCASIwDQYJKoZIhvcNAQEBBQADggEP\n"
"ADCCAQoCggEBAMCygZOgwRlUls6U3CjzLD77+ruZiPY80OKc52T7lLtIbuclTPMi\n"
"gd8rl7vwrJFbyCdNd2RlpvjvV8ZHoAbuKrf+pgBAMjT1BsKY+W2MFA8XKoNfoUuf\n"
"yYQSmM59tcQ8gxxCpDnw1ZfDN9C61/Ucb3zzN0d4tSGPcsIpT0f5e3dhUbElXzer\n"
"V7d2znQpwWhP0EwI2rDSRbun2GNX7JeP5EzRWrOAwh5xwp0ZuV5irLfHxSVNgCYr\n"
"33tf9EcPnWATcLY6GybLzVKRUrRB90bWHD712yxhPfliQGCgoOxrQQzQrfH8heAu\n"
"y9900WeAR0X/ru4dtvxLNrIV88CUUCsLA8MCAwEAAaOCAjUwggIxMA4GA1UdDwEB\n"
"/wQEAwIFoDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwDAYDVR0TAQH/\n"
"BAIwADAdBgNVHQ4EFgQUBtvAXfOnnmL56Njc066vuC+e/iUwHwYDVR0jBBgwFoAU\n"
"u7zDR6XkvKnGw6RyDBCNojXhyOgwVwYIKwYBBQUHAQEESzBJMCIGCCsGAQUFBzAB\n"
"hhZodHRwOi8vcjEwLm8ubGVuY3Iub3JnMCMGCCsGAQUFBzAChhdodHRwOi8vcjEw\n"
"LmkubGVuY3Iub3JnLzA9BgNVHREENjA0ghkqLnNvbmdhdGVjaG5vbG9naWVzLmNv\n"
"Lmtlghdzb25nYXRlY2hub2xvZ2llcy5jby5rZTATBgNVHSAEDDAKMAgGBmeBDAEC\n"
"ATCCAQMGCisGAQQB1nkCBAIEgfQEgfEA7wB1AM8RVu7VLnyv84db2Wkum+kacWdK\n"
"sBfsrAHSW3fOzDsIAAABky9W7a0AAAQDAEYwRAIgF7RmbNnIWjH/4YwPY/85+x/j\n"
"KY+mRpiT8ivv+V9pieUCIEIxm2z97AmomjEPKlUIiiNUZ3RqfcQFHiMaQXxm+Bir\n"
"AHYA4JKz/AwdyOdoNh/eYbmWTQpSeBmKctZyxLBNpW1vVAQAAAGTL1btxgAABAMA\n"
"RzBFAiBB4fP2HeSsE/ubwVdHPI71ClO/ZKCwQZqduElT9EpubQIhANljPUvrJj2Z\n"
"mondMEsb7EzV+k5u1m+CDLN1hh548K6eMA0GCSqGSIb3DQEBCwUAA4IBAQCgqP++\n"
"FJqLc+4IKOEUdRWu0f81L7RFvpw22QsuosVsJzQwYlG/vIu/b8eI8XW30p01Y3GR\n"
"E3zZj2kWlxcTzbUYu75vwjcSomsjn9NT/p7apd/Ce17ztr9TDmWLtK2eob3CMUTQ\n"
"POmKNIoMLFjq2yeYfPFKGin7lPN4v50P0ZnS/HBK5Np6wFDa9SjARZR1o2djquzq\n"
"o+bgRPacpxpZ9JiOqPPOUClTURBUeS9DlaFznGwfdf+9QozJMHScF7sowgQxU83H\n"
"NCvEbkNAJ0qcmVw5QTjVN/gutcVxFE0Rv6MiPdpFgS+j2gHqExaeeKyQqFlQOCXq\n"
"iXDZP0OUsxon38R+\n"
"-----END CERTIFICATE-----\n";

#endif
